#!/usr/bin/env bash
{{- if eq .host.distro.id "freebsd" }}

# Required for styled logging
{{- includeTemplate "universal/logg" }}

{{- $packages := splitList " " (includeTemplate "universal/essential-packages" .) }}
# TODO - Add Python dependencies like in ubuntu/archlinux

logg 'Installing common dependencies using pkg'
logg "Dependencies: {{ $packages | sortAlpha | uniq | join " " -}}"

### Install base dependencies
sudo pkg install -y {{ $packages | sortAlpha | uniq | join " " -}}
{{- end }}

