# Base dependencies required for deploying on macOS. Defined like this because Homebrew
# is a requirement on macOS.

# Standard Homebrew taps
tap "homebrew/cask-versions" # Initially added to support "visual-studio" cask
tap "homebrew/core"
tap "homebrew/bundle"

if OS.mac?
  brew "coreutils"
  brew "findutils"
  brew "m-cli"
end
brew "age"
brew "asdf"
brew "glow"
brew "gnupg"
brew "gum"
brew "jq"
brew "node"
tap "go-task/tap"
brew "go-task/tap/go-task"
brew "volta"
brew "yq"
brew "zx"
