#!/bin/sh
# Start up the standard system desktop
# Source: https://www.tecmint.com/install-and-configure-vnc-server-on-ubuntu/

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
vncconfig -iconic &
dbus-launch --exit-with-session gnome-session &
