#!/usr/bin/env bash

{{ includeTemplate "universal/profile" }}
{{ includeTemplate "universal/logg" }}

logg info 'Ensure /usr/local/share/grub/themes is a directory'
sudo mkdir -p /usr/local/share/grub/themes

logg info 'Copy GRUB theme to /usr/local/share/grub/themes'
cp -rf /usr/local/src/{{ .theme }}/share/grub/themes/ /usr/local/share/grub/themes

logg info 'Ensure /boot/grub2/themes is a directory'
sudo mkdir -p /boot/grub2/themes

logg info 'Copy GRUB themes to /boot/grub2/themes'
sudo cp -rf /usr/local/share/grub/themes/ /boot/grub2/themes