#!/usr/bin/env bash
{{- if eq .host.distro.id "opensuse" }}

# Required for styled logging
{{- includeTemplate "universal/logg" }}

{{- $packages := splitList " " (includeTemplate "universal/essential-packages" .) }}
# TODO - Add Python dependencies like in ubuntu/archlinux

logg 'Installing common dependencies using zypper'
logg "Dependencies: {{ $packages | sortAlpha | uniq | join " " -}}"

### Install base dependencies
sudo zypper install -y {{ $packages | sortAlpha | uniq | join " " -}}

{{- end -}}
