" Install Coc extensions
" TODO: Add https://github.com/yuki-yano/fzf-preview.vim
" TODO: Add https://github.com/tpope/vim-fugitive
if executable('node')
  let g:coc_global_config="$HOME/.config/coc/coc-settings.json"
  let g:coc_global_extensions = [
    \ '@yaegassy/coc-ansible',
    \ '@yaegassy/coc-nginx',
    \ 'coc-angular',
    \ 'coc-blade',
    \ 'coc-calc',
    \ 'coc-clangd',
    \ 'coc-copilot',
    \ 'coc-css',
    \ 'coc-cssmodules',
    \ 'coc-deno',
    \ 'coc-diagnostic',
    \ 'coc-docker',
    \ 'coc-emmet',
    \ 'coc-eslint',
    \ 'coc-explorer',
    \ 'coc-flutter',
    \ 'coc-git',
    \ 'coc-go',
    \ 'coc-highlight',
    \ 'coc-html-css-support',
    \ 'coc-html',
    \ 'coc-htmlhint',
    \ 'coc-java',
    \ 'coc-jedi',
    \ 'coc-json',
    \ 'coc-ltex',
    \ 'coc-lua',
    \ 'coc-markdown-preview-enhanced',
    \ 'coc-markdownlint',
    \ 'coc-markmap',
    \ 'coc-phpls',
    \ 'coc-powershell',
    \ 'coc-prettier',
    \ 'coc-prisma',
    \ 'coc-pyright',
    \ 'coc-rls',
    \ 'coc-rust-analyzer',
    \ 'coc-sh',
    \ 'coc-solargraph',
    \ 'coc-solidity',
    \ 'coc-spell-checker',
    \ 'coc-stylelint',
    \ 'coc-sql',
    \ 'coc-sqlfluff',
    \ 'coc-svelte',
    \ 'coc-svg',
    \ 'coc-swagger',
    \ 'coc-symbol-line',
    \ 'coc-tailwindcss',
    \ 'coc-toml',
    \ 'coc-tsserver',
    \ 'coc-xml',
    \ 'coc-yaml',
    \ 'coc-yank'
    \]
endif

" Settings for coc-css extension
autocmd FileType scss setl iskeyword+=@-@

" Settings for coc-go extension, to add missing imports on save
autocmd BufWritePre *.go :silent call CocAction('runCommand', 'editor.action.organizeImport')

syntax enable
set background=dark
colorscheme Betelgeuse
" set g:lightline = { 'colorscheme': 'Betelgeuse' }

" Settings for plugin https://github.com/neoclide/coc.nvim.git
autocmd FileType json syntax match Comment +\/\/.\+$+

" Settings for plugin https://github.com/vim-syntastic/syntastic.git
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Settings for plugin https://github.com/ryanoasis/vim-devicons.git
set encoding=UTF-8

" Set location of viminfo file
set viminfo+=n~/.config/vim/viminfo

silent! call plug#begin()
Plug '~/.config/vim/plugged/ale'
Plug '~/.config/vim/plugged/copilot.vim'
Plug '~/.config/vim/plugged/dockerfile.vim'
Plug '~/.config/vim/plugged/editorconfig-vim'
Plug '~/.config/vim/plugged/fzf.vim'
Plug '~/.config/vim/plugged/fzf'
Plug '~/.config/vim/plugged/lightline.vim'
Plug '~/.config/vim/plugged/nerdtree'
Plug '~/.config/vim/plugged/php.vim'
Plug '~/.config/vim/plugged/python-syntax'
Plug '~/.config/vim/plugged/syntastic'
Plug '~/.config/vim/plugged/typescript-vim'
Plug '~/.config/vim/plugged/vim-airline'
Plug '~/.config/vim/plugged/vim-carbon-now-sh'
Plug '~/.config/vim/plugged/vim-devicons'
Plug '~/.config/vim/plugged/vim-five'
Plug '~/.config/vim/plugged/vim-go'
Plug '~/.config/vim/plugged/vim-javascript'
Plug '~/.config/vim/plugged/vim-jsx'
Plug '~/.config/vim/plugged/vim-markdown'
Plug '~/.config/vim/plugged/vim-multiple-cursors'
Plug '~/.config/vim/plugged/vim-prettier'
Plug '~/.config/vim/plugged/vim-sensible'
Plug '~/.config/vim/plugged/vim-surround'
Plug '~/.config/vim/plugged/vimgutter'
Plug '~/.config/vim/plugged/zoxide.vim'
if executable('node')
  Plug '~/.config/vim/plugged/coc.nvim'
endif
Plug '~/.config/vim/plugged/ansible-vim', {'do': './UltiSnips/generate.sh'}
call plug#end()

