#!/usr/bin/expect
# TODO: https://github.com/hyperupcall/dots/tree/8e62ad19f4fa870bd70b1816d383bc32e9b6d149/dotmgr
# https://www.chezmoi.io/user-guide/frequently-asked-questions/encryption/#how-do-i-configure-chezmoi-to-encrypt-files-but-only-request-a-passphrase-the-first-time-chezmoi-init-is-run
# Figure out way of not writing AGE_PASSPHRASE to disk - keep in mem

spawn ./test.bash
expect "Enter passphrase*"
send -- "{{ .Env.AGE_PASSPHRASE }}\r"
expect "Confirm passphrase*"
send -- "{{ .Env.AGE_PASSPHRASE }}\r"
expect eof
