#!/usr/bin/env bash
{{- if eq .host.distro.id "arch" }}
{{ $supportedManagers := (list "flatpak" "snap" "whalebrew" "pacman" "brew" "yay" "go" "cargo" "npm" "pipx" "gem" "appimage" "binary") }}

{{- end }}
