---
# When set to true, ssh-keyscan will be performed on all the other clients
add_known_hosts: true

default_browser: brave

software:
  - act
  - altair
  - askgit
  - azurefunctions
  - bandwhich
  - bane
  - bat
  - betwixt
  - bin
  - bitwarden
  - bivac
  - boilr
  - captain
  - cerebro
  - clair
  - consul
  - croc
  - ctop
  - cumulus
  - dasel
  - dat
  - delta
  - desed
  - deta
  - direnv
  - dive
  - docker
  - dockle
  - doctl
  - dog
  - duf
  - dust
  - envconsul
  - fd
  #  - felony # No releases in 6 years, no 'latest' release tag ever which causes the `gh` method to fail
  - ffsend
  - filebrowser
  - fm
  - fq
  - fselect
  - fuego
  #  - g-assist # A separate Role exists
  - ganache
  - gitify
  - gitleaks
  - gitomatic
  - glab
  - glow
  - go
  - gojq
  - gping
  - grex
  - gron
  - hclq
  - hexyl
  - hey
  - hostctl
  - htmlq
  - hyperfine
  - jiq
  - jitsi
  - jo
  - jq
  - kdash
  - kubenav
  - license
  - linuxkit
  - manta
  - mark
  - masscode
  - mc
  - mergestat
  - mjml
  - mkcert
  - mockoon
  - motrix
  - mqttx
  - muffet
  #  - mullvad-vpn # deb, rpm available, no archives for Linux
  - nebula
  - nnn
  - node
  - nomino
  - nuclear
  - oq
  - osquery
  - ots
  - page
  - pass
  - pastel
  - peco
  - pony
  - pretzel # Mac only, over 3 years old
  - procs
  #  - psu # Releases contain only code. few pre-releases contain releases, no update in about 2.5 years
  - pup
  - q
  - raindrop
  - responsively
  - rip
  - runjs
  - s5cmd
  - schema
  - scrcpy
  - sd
  - shfmt
  - skm
  #   - sqlectron # deb, rpm, pacman available but no archive
  - ssh-vault
  - ssl-proxy
  - skype
  - slack
  - sqlectron
  - ssh
  - ssl
  - switchhosts
  - sysbench
  - tabby
  - task
  - teleport
  - temps # 6 years old. Forks are platform specific
  - tflint
  - tokei
  - transfer
  - trivy
  - udemy
  - up
  - waypoint
  - websocat
  - webtorrent
  - whaler
  - wkhtmltopdf
  - xurls
  - yq

vpn_connections:
  - file: OpenVPN.ovpn
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: WireGuard.nmconnection
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
