---
# @var add_known_hosts: true # When set to `true`, the playbook will automatically attempt to pre-cache
# SSH address signatures into the `known_hosts` file.
add_known_hosts: true

default_ssh_authorized_keys:
  - "{{ lookup('file', 'files/ssh/id_ecdsa_sk_onlykey_green.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ecdsa_sk_onlykey_green_alt.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ecdsa_sk_onlykey_green_x.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ed25519_sk_26.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ed25519_sk_27.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ed25519_sk_52.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ed25519_sk_yubi_nano.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ed25519_sk_yubi_nano_x.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ed25519_sk_yubi_nanoc.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ed25519_sk_yubi_nanoc_x.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ed25519_sk_yubi_nfc_green.pub') }}"
  - "{{ lookup('file', 'files/ssh/id_ed25519_sk_yubi_nfc_green_x.pub') }}"

default_ssh_private_keys:
  - files/ssh/id_ecdsa_sk_onlykey_green
  - files/ssh/id_ecdsa_sk_onlykey_green_alt
  - files/ssh/id_ecdsa_sk_onlykey_green_x
  - files/ssh/id_ed25519_sk_26
  - files/ssh/id_ed25519_sk_27
  - files/ssh/id_ed25519_sk_52
  - files/ssh/id_ed25519_sk_yubi_nano
  - files/ssh/id_ed25519_sk_yubi_nano_x
  - files/ssh/id_ed25519_sk_yubi_nanoc
  - files/ssh/id_ed25519_sk_yubi_nanoc_x
  - files/ssh/id_ed25519_sk_yubi_nfc_green
  - files/ssh/id_ed25519_sk_yubi_nfc_green_x
  - files/ssh/id_rsa

# @var software: [] # A list of software packages to be installed via the `roles/helpers/installer` role. The list of software
# that can be installed via the role (and this variable) is in `group_vars/all/software.yml`.
software:
  - act
  - altair
  - askgit
  - azurefunctions
  - bandwhich
  - bane
  - bat
  - betwixt
  - bin
  - bitwarden
  - bivac
  - boilr
  - captain
  - cerebro
  - clair
  - consul
  - croc
  - ctop
  - cumulus
  - dasel
  - dat
  - delta
  - desed
  - deta
  - direnv
  - dive
  - docker
  - dockle
  - doctl
  - dog
  - duf
  - dust
  - envconsul
  - fd
  # No releases in 6 years, no 'latest' release tag ever which causes the `gh` method to fail
  # - felony
  - ffsend
  - filebrowser
  - fm
  - fq
  - fselect
  - fuego
  # A separate Role exists
  # - g-assist
  - gitify
  - gitleaks
  - gitomatic
  - glab
  - glow
  - go
  - gojq
  - gping
  - grex
  - gron
  - hclq
  - hexyl
  - hey
  - hostctl
  - htmlq
  - hyperfine
  - jiq
  - jitsi
  - jo
  - jq
  - kdash
  # Looks like it was primarily designed for mobile and it only has a GitHub release
  # - kubenav
  - license
  - linuxkit
  - manta
  - mark
  - masscode
  - mc
  - mergestat
  - mjml
  - mkcert
  - mockoon
  - motrix
  - mqttx
  - muffet
  #  - mullvad-vpn # deb, rpm available, no archives for Linux
  - nebula
  - nnn
  - node
  - nomino
  - nuclear
  - oq
  - osquery
  - ots
  - page
  - pass
  - pastel
  - peco
  - pony
  - pretzel # Mac only, over 3 years old
  - procs
  #  - psu # Releases contain only code. few pre-releases contain releases, no update in about 2.5 years
  - pup
  - q
  - raindrop
  - responsively
  - rip
  - runjs
  - s5cmd
  - schema
  - scrcpy
  - sd
  - shfmt
  - skm
  #   - sqlectron # deb, rpm, pacman available but no archive
  - ssh-vault
  - ssl-proxy
  - skype
  - slack
  - sqlectron
  - ssh
  - ssl
  - switchhosts
  - sysbench
  - tabby
  - task
  - teleport
  - temps # 6 years old. Forks are platform specific
  - tflint
  - tokei
  - transfer
  - trivy
  - udemy
  - up
  - waypoint
  - websocat
  - webtorrent
  - whaler
  - wkhtmltopdf
  - xurls
  - yq

# @var default_browser: brave # Set this variable equal to the tag corresponding to the browser you wish to be set as the default browser.
# Available options include `brave` (Brave Browser), `firefox` (Firefox), `edge` (Microsoft Edge), and `chrome` (Google Chrome / Chromium).
default_browser: brave

# @var vpn_connections: [] # A list of VPN profiles to automatically load into the NetworkManager VPN plugin on Linux and into the WireGuard
# app on macOS / Linux. The profiles should be placed in the `files/vpn` folder. Examples of OpenVPN / WireGuard profiles are also available
# in that folder.
vpn_connections:
  - file: Mullvad WG Belgium (UDP 4888).nmconnection
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: Mullvad WG Japan (UDP 4888).nmconnection
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: Mullvad WG Moldova (UDP 53).nmconnection
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: Mullvad WG Singapore (UDP 4888).nmconnection
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: Proton WG Cambodia (UDP 51820).nmconnection
    password: '{{ proton_password }}'
    username: '{{ proton_username }}'
  - file: Proton WG Colombia (UDP 51820).nmconnection
    password: '{{ proton_password }}'
    username: '{{ proton_username }}'
  - file: Proton WG Cyprus (UDP 51820).nmconnection
    password: '{{ proton_password }}'
    username: '{{ proton_username }}'
  - file: Proton WG Serbia (UDP 51820).nmconnection
    password: '{{ proton_password }}'
    username: '{{ proton_username }}'
  - file: Proton WG Slovakia (UDP 51820).nmconnection
    password: '{{ proton_password }}'
    username: '{{ proton_username }}'
  - file: Mullvad OVPN Greece (TCP 53).ovpn
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: Mullvad OVPN Los Angeles (TCP 443).ovpn
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: Mullvad OVPN Luxembourg (TCP 443).ovpn
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: Mullvad OVPN Romania (TCP 80).ovpn
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: Mullvad Shadowsocks Serbia (TCP 443+1080).ovpn
    password: '{{ mullvad_password }}'
    username: '{{ mullvad_username }}'
  - file: Proton OVPN Argentina (TCP 443+7770+8443).ovpn
    password: '{{ proton_openvpn_password }}'
    username: '{{ proton_openvpn_username }}'
  - file: Proton OVPN Finland (via Sweden) (TCP 443+7770+8443).ovpn
    password: '{{ proton_openvpn_password }}'
    username: '{{ proton_openvpn_username }}'
  - file: Proton OVPN France (TCP 443+7770+8443).ovpn
    password: '{{ proton_openvpn_password }}'
    username: '{{ proton_openvpn_username }}'
  - file: Proton OVPN Russia (via Iceland) (TCP 443+7770+8443).ovpn
    password: '{{ proton_openvpn_password }}'
    username: '{{ proton_openvpn_username }}'
  - file: Proton OVPN USA (TCP 443+7770+8443).ovpn
    password: '{{ proton_openvpn_password }}'
    username: '{{ proton_openvpn_username }}'
# @example #
# vpn_connections:
#   - file: Mullvad OpenVPN Denver (UDP 53).ovpn
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
#   - file: Mullvad OpenVPN Hong Kong.ovpn
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
#   - file: Mullvad OpenVPN Italy.ovpn
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
#   - file: Mullvad OpenVPN NYC.ovpn
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
#   - file: Mullvad OpenVPN Secaucus (TCP 80).ovpn
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
#   - file: Mullvad WireGuard Germany (Custom Port).nmconnection
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
#   - file: Mullvad WireGuard Italy Brazil.nmconnection
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
#   - file: Mullvad WireGuard NYC (Custom Port).nmconnection
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
#   - file: Mullvad WireGuard NYC.nmconnection
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
#   - file: Mullvad WireGuard Switzerland.nmconnection
#     password: '{{ mullvad_password }}'
#     username: '{{ mullvad_username }}'
# @end
